[package]
name = "advent"
version = "0.0.1"
authors = [
    "Tim Anderson <tim.anderson@umontana.edu"
]
edition = "2021"

[dependencies]
anyhow = "1.0.93"
regex = "1.11.1"
reqwest = "0.12.9"
text_io = "0.1.12"
tokio = "1.41.1"
